import { useState, useEffect } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { getErrorMessage } from '../utils/api';
import toast from 'react-hot-toast';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

export default function TwoFactorChallenge() {
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const { verifyMfa } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  // Get mfa_token from router state
  const mfa_token = location.state?.mfa_token;

  useEffect(() => {
    // If no mfa_token is present in state, redirect back to login
    if (!mfa_token) {
      toast.error('Session expired. Please log in again.');
      navigate('/login', { replace: true });
    }
  }, [mfa_token, navigate]);

  const handleSubmit = async e => {
    e.preventDefault();
    if (code.length !== 6) {
      return toast.error('Please enter a 6-digit code');
    }
    setLoading(true);
    try {
      await verifyMfa(mfa_token, code);
      toast.success('Logged in successfully');
      navigate('/');
    } catch (err) {
      toast.error(getErrorMessage(err, 'Invalid verification code'));
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = e => {
    // Only allow numeric input
    const val = e.target.value.replace(/[^0-9]/g, '');
    if (val.length <= 6) {
      setCode(val);
    }
  };

  return (
    <div className="login-page">
      <div className="login-card" style={{
        animation: 'fadeIn 0.3s ease-out'
      }}>
        {/* Header/Logo mimicking Login.jsx to maintain exact branding */}
        <div className="login-logo">
          <div className="logo-icon">K</div>
          <div>
            <div className="logo-text">KIM ERP</div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', marginBottom: 24 }}>
          <div style={{
            width: 48,
            height: 48,
            borderRadius: '10px',
            background: 'var(--accent-dim)',
            color: 'var(--accent)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 12
          }}>
            <ShieldCheck size={24} />
          </div>
          <h2 style={{ fontSize: 16, fontWeight: 700, margin: '0 0 6px 0', color: 'var(--text)' }}>Security Verification</h2>
          <p style={{ fontSize: 12.5, color: 'var(--text3)', margin: 0, lineHeight: 1.4 }}>
            Enter the 6-digit code generated by your Google Authenticator or Microsoft Authenticator app to continue.
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="form-grid" style={{ gap: 16 }}>
            <div className="form-group">
              <input
                className="form-input"
                type="text"
                pattern="[0-9]*"
                inputMode="numeric"
                maxLength={6}
                value={code}
                onChange={handleInputChange}
                placeholder="000000"
                autoFocus
                required
                style={{
                  fontSize: 24,
                  letterSpacing: '8px',
                  textAlign: 'center',
                  fontWeight: 700,
                  height: '48px',
                  background: 'var(--bg3)',
                  border: '1.5px solid var(--border)',
                  color: 'var(--text)',
                  width: '100%',
                  paddingLeft: '14px', // offsets letter-spacing of last digit
                  outline: 'none',
                  borderRadius: 'var(--radius-sm)'
                }}
              />
            </div>
            
            <button className="btn btn-primary w-full" type="submit" disabled={loading} style={{
              height: '42px',
              justifyContent: 'center',
              borderRadius: 'var(--radius-sm)'
            }}>
              {loading ? <div className="spinner" style={{ width: 16, height: 16, borderTopColor: '#fff' }} /> : 'Verify & Sign In'}
            </button>
          </div>
        </form>

        <div style={{ marginTop: 20, textAlign: 'center' }}>
          <Link to="/login" style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            fontSize: 13,
            fontWeight: 600,
            color: 'var(--text3)',
            textDecoration: 'none',
            transition: 'color 0.2s'
          }}
          onMouseEnter={e => e.currentTarget.style.color = 'var(--accent)'}
          onMouseLeave={e => e.currentTarget.style.color = 'var(--text3)'}>
            <ArrowLeft size={14} /> Back to Sign In
          </Link>
        </div>
      </div>
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
}
