import { useState, useEffect } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { getErrorMessage } from '../utils/api';
import toast from 'react-hot-toast';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

export default function TwoFactorChallenge() {
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const { verifyMfa } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  // Get mfa_token from router state
  const mfa_token = location.state?.mfa_token;

  useEffect(() => {
    // If no mfa_token is present in state, redirect back to login
    if (!mfa_token) {
      toast.error('Session expired. Please log in again.');
      navigate('/login', { replace: true });
    }
  }, [mfa_token, navigate]);

  const handleSubmit = async e => {
    e.preventDefault();
    if (code.length !== 6) {
      return toast.error('Please enter a 6-digit code');
    }
    setLoading(true);
    try {
      await verifyMfa(mfa_token, code);
      toast.success('Logged in successfully');
      navigate('/');
    } catch (err) {
      toast.error(getErrorMessage(err, 'Invalid verification code'));
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = e => {
    // Only allow numeric input
    const val = e.target.value.replace(/[^0-9]/g, '');
    if (val.length <= 6) {
      setCode(val);
    }
  };

  return (
    <div className="login-page" style={{ background: 'radial-gradient(circle at 50% 50%, var(--bg) 0%, #0d0e15 100%)' }}>
      <div className="login-card" style={{
        background: 'rgba(30, 41, 59, 0.45)',
        backdropFilter: 'blur(16px)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        boxShadow: '0 20px 40px rgba(0, 0, 0, 0.3)',
        borderRadius: '24px',
        padding: '36px',
        animation: 'fadeIn 0.4s ease-out'
      }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', marginBottom: 28 }}>
          <div style={{
            width: 56,
            height: 56,
            borderRadius: '16px',
            background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.2) 0%, rgba(139, 92, 246, 0.2) 100%)',
            border: '1px solid rgba(99, 102, 241, 0.3)',
            color: 'var(--accent)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 16,
            boxShadow: '0 8px 16px rgba(99, 102, 241, 0.15)'
          }}>
            <ShieldCheck size={28} />
          </div>
          <h2 style={{ fontSize: 20, fontWeight: 800, margin: '0 0 8px 0', color: 'var(--text)' }}>Security Verification</h2>
          <p style={{ fontSize: 13, color: 'var(--text2)', margin: 0, lineHeight: 1.5 }}>
            Enter the 6-digit code generated by your Google Authenticator or Microsoft Authenticator app to continue.
          </p>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="form-grid" style={{ gap: 20 }}>
            <div className="form-group" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
              <input
                className="form-input"
                type="text"
                pattern="[0-9]*"
                inputMode="numeric"
                maxLength={6}
                value={code}
                onChange={handleInputChange}
                placeholder="000000"
                autoFocus
                required
                style={{
                  fontSize: 32,
                  letterSpacing: '12px',
                  textAlign: 'center',
                  fontWeight: 800,
                  height: '64px',
                  borderRadius: '14px',
                  border: '1.5px solid var(--border)',
                  background: 'rgba(15, 23, 42, 0.6)',
                  color: 'var(--text)',
                  width: '100%',
                  paddingLeft: '22px', // compensates for letter-spacing offset on the last char
                  outline: 'none',
                  transition: 'all 0.2s',
                  boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.2)'
                }}
              />
            </div>
            
            <button className="btn btn-primary w-full" type="submit" disabled={loading} style={{
              height: '46px',
              borderRadius: '12px',
              fontSize: 14,
              fontWeight: 700,
              boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)',
              background: 'linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)',
              border: 'none',
              cursor: 'pointer',
              color: '#fff',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 8,
              transition: 'all 0.2s'
            }}>
              {loading ? <div className="spinner" style={{ width: 18, height: 18, borderTopColor: '#fff' }} /> : 'Verify & Sign In'}
            </button>
          </div>
        </form>

        <div style={{ marginTop: 24, textAlign: 'center' }}>
          <Link to="/login" style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            fontSize: 13,
            fontWeight: 600,
            color: 'var(--text2)',
            textDecoration: 'none',
            transition: 'color 0.2s'
          }}
          onMouseEnter={e => e.currentTarget.style.color = 'var(--text)'}
          onMouseLeave={e => e.currentTarget.style.color = 'var(--text2)'}>
            <ArrowLeft size={14} /> Back to Sign In
          </Link>
        </div>
      </div>
      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(12px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
}
